[package]
name = "wfcache-api"
version = "0.4.0"
edition = "2021"
authors = ["Youn Mélois <youn@melois.dev>"]
repository = "https://github.com/sehnryr/wfcache-api"
homepage = "https://github.com/sehnryr/wfcache-api"
description = "Application that allows you to read and extract data from Warframe's cache files programmatically"
readme = "README.md"
license = "GPL-3.0-or-later"
keywords = ["warframe", "cache", "decompression", "cli"]
categories = ["command-line-utilities"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.69"
clap = { version = "4.1.4", features = ["derive"] }
crc = "3.0.1"
ddsfile = "0.5.1"
derivative = "2.2.0"
env_logger = "0.10.0"
log = "0.4.17"
lotus-lib = "2.*"
rand = "0.8.5"
relative-path = "1.7.3"
rustyline = "10.1.1"
serde_json = "1.0.93"
yansi = "0.5.1"
