[package]
name = "wfcache-api"
version = "0.9.2"
edition = "2021"
authors = ["Youn Mélois <youn@melois.dev>"]
repository = "https://github.com/sehnryr/wfcache-api"
homepage = "https://github.com/sehnryr/wfcache-api"
description = "Application that allows you to read and extract data from Warframe's cache files programmatically"
readme = "README.md"
license = "GPL-3.0-or-later"
keywords = ["warframe", "cache", "decompression", "cli"]
categories = ["command-line-utilities"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.*"
clap = { version = "4.1.*", features = ["derive"] }
crc = "3.0.*"
ddsfile = "0.5.*"
derivative = "2.2.*"
env_logger = "0.10.*"
log = "0.4.*"
lotus-lib = { version = "3.0.*", features = ["internal"] }
lscolors = "0.13.*"
rand = "0.8.*"
relative-path = "1.7.*"
rustyline = "10.1.*"
serde_json = "1.0.*"
term_grid = "0.1.*"
terminal_size = "0.2.*"
